# Generated by Django 5.0.3 on 2025-01-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_condition',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
