# Generated by Django 5.0.3 on 2025-01-16 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecc', '0003_alter_products_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
