# Generated by Django 5.0.3 on 2025-01-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecc', '0006_remove_products_product_image_upload_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
