# Generated by Django 5.0.3 on 2025-01-21 09:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecc', '0007_alter_products_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Created_At',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
