# Generated by Django 5.0.3 on 2025-01-30 13:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecc', '0008_products_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_images',
            name='product_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
