# Generated by Django 5.0.3 on 2025-02-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecc', '0009_alter_upload_images_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Approved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
